#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme 
title: Examining Collision Patterns and Trends for Safety of Autonomous Driving
description: False
show_downloads: False
theme: jekyll-theme-minimal
